### ISSUE TITLE
NOT WOKING!

### ISSUE THREAD

**Issue by xkajxkajx** [nguyenminh-phuc/TruyCapSteam#1]
When ruining it,it gives me this error:

![SShot 05 11 2024@08 57 48](https://github.com/user-attachments/assets/b13acc87-1ba5-40b5-bbd2-b3b23607368e)

Thanks

**Comment by nguyenminh-phuc** [comment]
Hi xkajxkajx, thanks for reporting this. Can you please give me a bit more detail?

First off, do you have any antivirus software running? Sometimes AV programs can block this app because it needs to install a system driver and runs with Admin rights.

Also, this app (like other DPI circumvention tools on Windows) uses WinDivert, a low-level driver. It sounds like for some reason, your system isn't allowing that driver to install which could be causing the error. I noticed you also had a similar problem with another DPI tool (https://github.com/strobecsmain/QuickNet-AntiDPI/issues/1) that uses zapret, which also relies on WinDivert. You might want to double check your system settings to make sure it's set up to allow driver installations.

**Comment by xkajxkajx** [comment]
Hi,

Of course I have an AV program (NOD32) but I think it not related simply because my AV should tell me about anything suspicious.

How do I check my system settings ( WIN 10 ) to make sure it's set up to allow driver installations?

Is the following command going to work with your tool? 

sc create "G:\TruyCapSteam" binPath= "G:\TruyCapSteam\TruyCapSteam.exe\"" start= "auto"

Thank you!

**Comment by nguyenminh-phuc** [comment]
Looks like either NOD32 or Windows Defender might be flagging the app and stopping it from running. To fix this, please try adding the app folder to the exclusion list for both antivirus programs. For Defender, go to *Windows Security > Virus & threat protection > Exclusions > Add or remove exclusions* and add the app folder there.

If you want to set this app up as a Windows service, you can do it by running this command:  
```  
.\TruyCapSteam.exe --install
```

Or you could go with `sc.exe` and set it up manually:
```  
sc create TruyCapSteam binPath= "G:\TruyCapSteam\TruyCapSteam.exe  --run-as-service" start= "auto"  
sc start TruyCapSteam  
```
To remove the service, try these commands:
```  
sc stop TruyCapSteam
sc delete TruyCapSteam  
sc stop WinDivert  
sc delete WinDivert  
```

**Comment by xkajxkajx** [comment]
> Looks like either NOD32 or Windows Defender might be flagging the app and stopping it from running. To fix this, please try adding the app folder to the exclusion list for both antivirus programs. For Defender, go to Windows Security > Virus & threat protection > Exclusions > Add or remove exclusions and add the app folder there.

**Comment by xkajxkajx** [comment]
First of all, I don't wanna ask my AV to exclude any folder until I make sure that everything in that folder is not suspicious.! Sorry,this is too risky!. 

I have installed it as a service ,but still I got the same errors when I tried to start it:

![SShot 07 11 2024@06 25 39](https://github.com/user-attachments/assets/7eee4e3a-4c78-480f-9f16-20c74f6befe6)


![SShot 07 11 2024@06 27 51](https://github.com/user-attachments/assets/737eeb45-0f2b-4e50-afce-3b3c5fab2774)

Thanks!

**Comment by xkajxkajx** [comment]
I don't wanna ask my AV to exclude any folder until I make sure that the folder is not suspicious!?!.
Sorry,this is too risky!.

I have installed it as a service but I got the same errors when I tried to start it:

![SShot 07 11 2024@06 25 39](https://github.com/user-attachments/assets/8dbaabb6-4e5e-4868-a264-4e7b05075bc2)

![SShot 07 11 2024@06 27 51](https://github.com/user-attachments/assets/ff404c58-a658-46f8-9fa4-e12da4837a0f)

Thanks!

**Comment by nguyenminh-phuc** [comment]
Hi, yes it's fair to be cautious about installing this tool, especially since it needs permissions to install a system-level driver that runs in kernel mode (WinDivert). If you want to be extra safe you could build the project yourself, actually in my experience AVs tend to go easier on apps built directly on your machine so you're less likely to get false flags.

To build it, just open the project in VS Community or VSCode then do a release build. Everything you need is already in the project, so just hit build no extra setup for dependencies. The only prebuilt library included is WinDivert, which I downloaded from the original source (https://reqrypt.org/windivert.html). You can either use the existing prebuilt files or build WinDivert from source yourself if you want to be extra safe.

For why the Windows service mode failed, I checked the code and turns out we need quotes around the filepath before the `--run-as-service` argument (https://github.com/nguyenminh-phuc/TruyCapSteam/blob/main/src/ServiceClient.cpp#L65). Here's the correct command:
```
sc create TruyCapSteam binPath= "\"G:\TruyCapSteam\TruyCapSteam.exe\" --run-as-service" start= "auto"
```
